Update generator version in manual cli example (#802)
### Motivation

This solves the missing import issue described in
https://github.com/apple/swift-openapi-generator/issues/755

### Modifications

Update the version of generator in`Makefile`
Updated runtime versions to latest released version

### Result

Solved the `is not available due to missing import of defining module
'Foundation'` issue

```text
 13 | //===----------------------------------------------------------------------===//
 14 | import OpenAPIKit
 15 |
    | `- note: add import of module 'Foundation'
 16 | /// Represents a server variable and the function of generation that should be applied.
 17 | protocol ServerVariableGenerator {
    :
166 |             self.key = key
167 |             swiftSafeKey = context.safeNameGenerator.swiftMemberName(for: key)
168 |             enumName = context.safeNameGenerator.swiftTypeName(for: key.localizedCapitalized)
    |                                                                         `- error: property 'localizedCapitalized' is not available due to missing import of defining module 'Foundation'
169 |             self.variable = variable
170 |             self.enumValues = enumValues
/Volumes/w/src/github.com/apple/swift-openapi-generator/Examples/manual-generation-generator-cli-example/.swift-openapi-generator/Sources/_OpenAPIGeneratorCore/Translator/TypesTranslator/translateServersVariables.swift:168:73: error: property 'localizedCapitalized' is not available due to missing import of defining module 'Foundation'
 13 | //===----------------------------------------------------------------------===//
 14 | import OpenAPIKit
```

### Test Plan

Passed locally, `make generate` and `swift run`.